# Auto-generated from rfc3987 1.3.8

from _typeshed import Incomplete

basestring = str

def format_patterns(**names): ...

patterns: Incomplete

def get_compiled_pattern(rule, flags: int = ...): ...
def match(string, rule: str = ...): ...
def parse(string, rule: str = ...): ...
def compose(scheme: Incomplete | None = ..., authority: Incomplete | None = ..., path: Incomplete | None = ..., query: Incomplete | None = ..., fragment: Incomplete | None = ..., iauthority: Incomplete | None = ..., ipath: Incomplete | None = ..., iquery: Incomplete | None = ..., ifragment: Incomplete | None = ..., **kw): ...
def resolve(base, uriref, strict: bool = ..., return_parts: bool = ...): ...
